services:
  # database
  database:
    env_file:
    - ./backend/.env
    image: postgres
    container_name: database
    ports:
      - "5433:5432"
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        DJANGO_CSRF_TRUSTED_ORIGINS: ${DJANGO_CSRF_TRUSTED_ORIGINS}
        DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
        DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
        DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
    - ./backend/.env
    command: >
      sh -c "
        python manage.py migrate &&
        chmod +x scripts/create_superuser.sh &&
        scripts/create_superuser.sh &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  flutter_web:
    container_name: flutter_web
    build:
      context: ./helth_mobile
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Flutter Web デフォルトポート
    volumes:
      - ./helth_mobile:/app
    working_dir: /app
    command: >
      bash -c "
        flutter pub get &&
        flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8080"

