
services:
  - type: web
    name: backend_server
    env: python
    buildCommand: ""
    startCommand: gunicorn your_project_name.wsgi:application
    autoDeploy: true
    plan: free
    branch: main
    region: oregon
    runtime: python
    rootDir: backend  # 必要に応じて調整（backend/にmanage.pyがある場合）
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "healthcare-backend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: backend_server-db
          property: connectionString

databases:
  - name: backend_server-db
