services:
  - type: web
    name: backend-server
    env: docker
    plan: free
    branch: main
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
      - key: DJANGO_ALLOWED_HOSTS
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
      - key: DJANGO_SUPERUSER_USERNAME
      - key: DJANGO_SUPERUSER_PASSWORD
      - key: DJANGO_SUPERUSER_EMAIL
      - key: POSTGRES_USER
      - key: POSTGRES_PASSWORD
      - key: POSTGRES_HOST
      - key: POSTGRES_DB
      - key: DATABASE_URL
        fromDatabase:
          name: backend_server_db  # ← Renderで作ったDBの名前と一致させる
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings  # settings.py の位置は決まっているためここだけ固定

databases:
  - name: backend-server-db
