# Generated by Django 5.2.4 on 2025-07-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0005_sleeprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
