# Generated by Django 5.2.4 on 2025-07-21 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0006_alter_weightrecord_month_alter_weightrecord_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('google_email', models.EmailField(max_length=254)),
                ('google_name', models.CharField(blank=True, max_length=255, null=True)),
                ('google_picture', models.URLField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
