# Generated by Django 5.2.4 on 2025-07-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0007_googleauthinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseAuthInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('firebase_email', models.EmailField(max_length=254)),
                ('firebase_name', models.CharField(blank=True, max_length=255, null=True)),
                ('firebase_picture', models.URLField(blank=True, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
